# Generated by Django 2.2.10 on 2021-09-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(verbose_name='Quiz start time'),
        ),
    ]
