# Generated by Django 2.2.10 on 2021-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210904_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedquiz',
            name='_answers',
            field=models.TextField(default=[], verbose_name='Answers'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
