version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/AppDocker
    depends_on:
      - db
    volumes:
      - ..:/app
      - ../static:/app/static
    expose:
      - 8000
    networks:
      - app-network
    ports:
      - 8000:8000
    command: "/bin/bash /app/deploy/app_prepare_and_run.sh"

  db:
    image: mysql
    networks:
      - app-network
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_quiz

  proxy:
    build:
      context: ..
      dockerfile: deploy/ProxyDocker
    depends_on:
      - app
    networks:
      - app-network
    ports:
      - 80:80
    volumes:
      - ../static/:/app/static
      - ../deploy:/nginxconfig

networks:
  app-network:
    driver: bridge
